language: php
php:
  - 7.2
services:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS app_main;'
before_script:
  - composer install --no-interaction
  - composer docs
  - composer migrate
  - php -S 127.0.0.1:8080 -t /home/travis/build/IVAgafonov/api-skeleton > /dev/null 2>&1 &
script:
  - composer test