language: php
php:
  - 7.2
before_script:
  - composer install --no-interaction
  - php -S 127.0.0.1:8080 -t /home/travis/build/IVAgafonov/api-skeleton > /dev/null 2>&1 &
  - composer docs
before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS app_main;'
  - composer migrate
script:
  - composer test